import { disconnect } from "process";

// import { Background } from './Background';
export const LoaderConfig = {
    // frame : "/src/sprites/SlotMachine_3x5.png",
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/GameBackground.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",    
    balancePanel :  "/src/sprites/PanelBalance.png",
    doubleButton: "src/sprites/doubleButton.png",
    winBg: "src/sprites/winBg.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    noteBox: "src/sprites/noteBox.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    PopupBackground: "src/sprites/popupBackground.png",
    messagePopup: "src/sprites/messagePopup.png",
    normalButton: "src/sprites/NormalButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinPopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    settingText: "src/sprites/SettingText.png",
    crossButton: "src/sprites/crossButton.png",
    crossButtonHover: "src/sprites/crossButtonHover.png",
    infoCross: "src/sprites/infoCross.png",
    disconnectClose: "src/sprites/closeButton.png",

    logo: "src/sprites/crazyMonkeyLogo.png",
    loadingText:"src/sprite/loadingText.png",
    assetsloader: "src/sprites/assetsloader.png",
    loaderBg: "src/sprites/loaderBg.png",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    roof:"src/sprites/Roof.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    headingImage: "src/sprites/PayTable_.png",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    soundPlus: "src/sprites/soundPlus.png",
    soundMinus: "src/sprites/soundMinus.png",
    soundIndicator: "src/sprites/Indicator.png",
    winningBg: "src/sprites/winningBg.png",
    winAmountPanel: "src/sprites/amountPanel.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    left0: "src/sprites/Colorfulleft1.png",
    left1: "src/sprites/Colorfulleft2.png",
    left2: "src/sprites/Colorfulleft3.png",
    left3: "src/sprites/Colorfulleft4.png",
    left4: "src/sprites/Colorfulleft5.png",
    left5: "src/sprites/Colorfulleft6.png",
    left6: "src/sprites/Colorfulleft7.png",
    left7: "src/sprites/Colorfulleft8.png",
    left8: "src/sprites/Colorfulleft9.png",


    leftHover0: "src/sprites/Blackleft1.png",
    leftHover1: "src/sprites/Blackleft2.png",
    leftHover2: "src/sprites/Blackleft3.png",
    leftHover3: "src/sprites/Blackleft4.png",
    leftHover4: "src/sprites/Blackleft5.png",
    leftHover5: "src/sprites/Blackleft6.png",
    leftHover6: "src/sprites/Blackleft7.png",
    leftHover7: "src/sprites/Blackleft8.png",
    leftHover8: "src/sprites/Blackleft9.png",

    right0: "src/sprites/Colorfulright1.png",
    right1: "src/sprites/Colorfulright2.png",
    right2: "src/sprites/Colorfulright3.png",
    right3: "src/sprites/Colorfulright4.png",
    right4: "src/sprites/Colorfulright5.png",
    right5: "src/sprites/Colorfulright6.png",
    right6: "src/sprites/Colorfulright7.png",
    right7: "src/sprites/Colorfulright8.png",
    right8: "src/sprites/Colorfulright9.png",

    rightHover0: "src/sprites/Blackright1.png",
    rightHover1: "src/sprites/Blackright2.png",
    rightHover2: "src/sprites/Blackright3.png",
    rightHover3: "src/sprites/Blackright4.png",
    rightHover4: "src/sprites/Blackright5.png",
    rightHover5: "src/sprites/Blackright6.png",
    rightHover6: "src/sprites/Blackright7.png",
    rightHover7: "src/sprites/Blackright8.png",
    rightHover8: "src/sprites/Blackright9.png",


    line0: "src/sprites/line1.png",
    line1: "src/sprites/line2.png",
    line2: "src/sprites/line3.png",
    line3: "src/sprites/line4.png",
    line4: "src/sprites/line5.png",
    line5: "src/sprites/line6.png",
    line6: "src/sprites/line7.png",
    line7: "src/sprites/line8.png",
    line8: "src/sprites/line9.png",

    Bail0: "src/sprites/Bail0.png",
    Bail1: "src/sprites/Bail1.png",
    Bail2: "src/sprites/Bail2.png",
    Bail3: "src/sprites/Bail3.png",
    Bail4: "src/sprites/Bail4.png",
    Bail5: "src/sprites/Bail5.png",
    Bail6: "src/sprites/Bail6.png",
    Bail7: "src/sprites/Bail7.png",
    Bail8: "src/sprites/Bail8.png",
    Bail9: "src/sprites/Bail9.png",
    Bail10: "src/sprites/Bail10.png",
    Bail11: "src/sprites/Bail11.png",
    Bail12: "src/sprites/Bail12.png",
    Bail13: "src/sprites/Bail13.png",
    Bail14: "src/sprites/Bail14.png",
    Bail15: "src/sprites/Bail15.png",
    Bail16: "src/sprites/Bail16.png",
    Bail17: "src/sprites/Bail17.png",
    Bail18: "src/sprites/Bail18.png",
    Bail19: "src/sprites/Bail19.png",
    Bail20: "src/sprites/Bail20.png",
    Bail21: "src/sprites/Bail21.png",
    Bail22: "src/sprites/Bail22.png",
    Bail23: "src/sprites/Bail23.png",
    Bail24: "src/sprites/Bail24.png",
    Bail25: "src/sprites/Bail25.png",
    Bail26: "src/sprites/Bail26.png",
    Bail27: "src/sprites/Bail27.png",
    Bail28: "src/sprites/Bail28.png",
    Bail29: "src/sprites/Bail29.png",

    coconutButton: "src/sprites/coconutButton.png",

    BackCard1: "src/sprites/Backcard1.png",
    BackCard2: "src/sprites/Backcard2.png",
    BackCard3: "src/sprites/Backcard3.png",
    Double: "src/sprites/withoutName.png",
    collectButton: "src/sprites/CollectButton.png",

    SpadesA:"src/sprites/spadeA.png",
    Spades2: "src/sprites/spade2.png",
    Spades3: "src/sprites/spade3.png",
    Spades4: "src/sprites/spade4.png",
    Spades5: "src/sprites/spade5.png",
    Spades6: "src/sprites/spade6.png",
    Spades7: "src/sprites/spade7.png",
    Spades8: "src/sprites/spade8.png",
    Spades9: "src/sprites/spade9.png",
    Spades10: "src/sprites/spade10.png",
    SpadesJ: "src/sprites/spadeJ.png",
    SpadesQ: "src/sprites/spadeQ.png",
    SpadesK: "src/sprites/spadeK.png",

    HeartsA: "src/sprites/HeartA.png",
    Hearts2: "src/sprites/Heart2.png",
    Hearts3: "src/sprites/Heart3.png",
    Hearts4: "src/sprites/Heart4.png",
    Hearts5: "src/sprites/Heart5.png",
    Hearts6: "src/sprites/Heart6.png",
    Hearts7: "src/sprites/Heart7.png",
    Hearts8: "src/sprites/Heart8.png",
    Hearts9: "src/sprites/Heart9.png",
    Hearts10: "src/sprites/Heart10.png",
    HeartsJ: "src/sprites/HeartJ.png",
    HeartsQ: "src/sprites/HeartQ.png",
    HeartsK: "src/sprites/HeartK.png",

    ClubsA: "src/sprites/ClubA.png",
    Clubs2: "src/sprites/Club2.png",
    Clubs3: "src/sprites/Club3.png",
    Clubs4: "src/sprites/Club4.png",
    Clubs5: "src/sprites/Club5.png",
    Clubs6: "src/sprites/Club6.png",
    Clubs7: "src/sprites/Club7.png",
    Clubs8: "src/sprites/Club8.png",
    Clubs9: "src/sprites/Club9.png",
    Clubs10: "src/sprites/Club10.png",
    ClubsJ: "src/sprites/ClubJ.png",
    ClubsQ: "src/sprites/ClubQ.png",
    ClubsK: "src/sprites/ClubK.png",

    DiamondsA: "src/sprites/DiamondA.png",
    Diamonds2: "src/sprites/Diamond2.png",
    Diamonds3: "src/sprites/Diamond3.png",
    Diamonds4: "src/sprites/Diamond4.png",
    Diamonds5: "src/sprites/Diamond5.png",
    Diamonds6: "src/sprites/Diamond6.png",
    Diamonds7: "src/sprites/Diamond7.png",
    Diamonds8: "src/sprites/Diamond8.png",
    Diamonds9: "src/sprites/Diamond9.png",
    Diamonds10: "src/sprites/Diamond10.png",
    DiamondsJ: "src/sprites/DiamondJ.png",
    DiamondsQ: "src/sprites/DiamondQ.png",
    DiamondsK: "src/sprites/DiamondK.png",

    coconutAnim0: "src/sprites/coconutanim1.png",
    coconutAnim1: "src/sprites/coconutanim2.png",
    coconutAnim2: "src/sprites/coconutanim3.png",
    coconutAnim3: "src/sprites/coconutanim4.png",
    coconutAnim4: "src/sprites/coconutanim5.png",
    coconutAnim5: "src/sprites/coconutanim6.png",
    coconutAnim6: "src/sprites/coconutanim7.png",
    coconutAnim7: "src/sprites/coconutanim8.png",
    coconutAnim8: "src/sprites/coconutanim9.png",
    coconutAnim9: "src/sprites/coconutanim10.png",
    coconutAnim10: "src/sprites/coconutanim11.png",
    coconutAnim11: "src/sprites/coconutanim12.png",
    coconutAnim12: "src/sprites/coconutanim13.png",
    coconutAnim13: "src/sprites/coconutanim14.png",
    coconutAnim14: "src/sprites/coconutanim15.png",
    coconutAnim15: "src/sprites/coconutanim16.png",
    coconutAnim16: "src/sprites/coconutanim17.png",
    coconutAnim17: "src/sprites/coconutanim18.png",
    coconutAnim18: "src/sprites/coconutanim19.png",
    coconutAnim19: "src/sprites/coconutanim20.png",
    coconutAnim20: "src/sprites/coconutanim21.png",
    coconutAnim21: "src/sprites/coconutanim22.png",
    coconutAnim22: "src/sprites/coconutanim23.png",
    coconutAnim23: "src/sprites/coconutanim24.png",
    coconutAnim24: "src/sprites/coconutanim25.png",
    coconutAnim25: "src/sprites/coconutanim26.png",
    coconutAnim26: "src/sprites/coconutanim27.png",
    coconutAnim27: "src/sprites/coconutanim28.png",
    coconutAnim28: "src/sprites/coconutanim29.png",
    coconutAnim29: "src/sprites/coconutanim30.png",
    coconutAnim30: "src/sprites/coconutanim31.png",
    coconutAnim31: "src/sprites/coconutanim32.png",
    coconutAnim32: "src/sprites/coconutanim33.png",
    coconutAnim33: "src/sprites/coconutanim34.png",
    coconutAnim34: "src/sprites/coconutanim35.png",
    coconutAnim35: "src/sprites/coconutanim36.png",
    coconutAnim36: "src/sprites/coconutanim37.png",
    coconutAnim37: "src/sprites/coconutanim38.png",
    coconutAnim38: "src/sprites/coconutanim39.png",
    coconutAnim39: "src/sprites/coconutanim40.png",
    coconutAnim40: "src/sprites/coconutanim41.png",
    coconutAnim41: "src/sprites/coconutanim42.png",
    coconutAnim42: "src/sprites/coconutanim43.png",
    coconutAnim43: "src/sprites/coconutanim44.png",
    coconutAnim44: "src/sprites/coconutanim45.png",
    coconutAnim45: "src/sprites/coconutanim46.png",
    coconutAnim46: "src/sprites/coconutanim47.png",
    coconutAnim47: "src/sprites/coconutanim48.png",



    slots0_0 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_1 :  "/src/sprites/Symbols/Monkey/Monkeyicon1.png",
    slots0_2 :  "/src/sprites/Symbols/Monkey/Monkeyicon2.png",
    slots0_3 :  "/src/sprites/Symbols/Monkey/Monkeyicon3.png",
    slots0_4 :  "/src/sprites/Symbols/Monkey/Monkeyicon4.png",
    slots0_5 :  "/src/sprites/Symbols/Monkey/Monkeyicon5.png",
    slots0_6 :  "/src/sprites/Symbols/Monkey/Monkeyicon6.png",
    slots0_7 :  "/src/sprites/Symbols/Monkey/Monkeyicon7.png",
    slots0_8 :  "/src/sprites/Symbols/Monkey/Monkeyicon8.png",
    slots0_9 :  "/src/sprites/Symbols/Monkey/Monkeyicon9.png",
    slots0_10:  "/src/sprites/Symbols/Monkey/Monkeyicon10.png",
    slots0_11:  "/src/sprites/Symbols/Monkey/Monkeyicon11.png",
    slots0_12:  "/src/sprites/Symbols/Monkey/Monkeyicon12.png",
    slots0_13:  "/src/sprites/Symbols/Monkey/Monkeyicon13.png",
    slots0_14:  "/src/sprites/Symbols/Monkey/Monkeyicon14.png",
    slots0_15:  "/src/sprites/Symbols/Monkey/Monkeyicon15.png",
    slots0_16:  "/src/sprites/Symbols/Monkey/Monkeyicon16.png",
    slots0_17:  "/src/sprites/Symbols/Monkey/Monkeyicon17.png",
    slots0_18:  "/src/sprites/Symbols/Monkey/Monkeyicon18.png",
    slots0_19:  "/src/sprites/Symbols/Monkey/Monkeyicon19.png",
    slots0_20:  "/src/sprites/Symbols/Monkey/Monkeyicon20.png",


    slots1_0 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_1 :  "/src/sprites/Symbols/Banana/Bananaicon1.png",
    slots1_2 :  "/src/sprites/Symbols/Banana/Bananaicon2.png",
    slots1_3 :  "/src/sprites/Symbols/Banana/Bananaicon3.png",
    slots1_4 :  "/src/sprites/Symbols/Banana/Bananaicon4.png",
    slots1_5 :  "/src/sprites/Symbols/Banana/Bananaicon5.png",
    slots1_6 :  "/src/sprites/Symbols/Banana/Bananaicon6.png",
    slots1_7 :  "/src/sprites/Symbols/Banana/Bananaicon7.png",
    slots1_8 :  "/src/sprites/Symbols/Banana/Bananaicon8.png",
    slots1_9 :  "/src/sprites/Symbols/Banana/Bananaicon9.png",
    slots1_10:  "/src/sprites/Symbols/Banana/Bananaicon10.png",
    slots1_11:  "/src/sprites/Symbols/Banana/Bananaicon11.png",
    slots1_12:  "/src/sprites/Symbols/Banana/Bananaicon12.png",
    slots1_13:  "/src/sprites/Symbols/Banana/Bananaicon13.png",
    slots1_14:  "/src/sprites/Symbols/Banana/Bananaicon14.png",
    slots1_15:  "/src/sprites/Symbols/Banana/Bananaicon15.png",
    slots1_16:  "/src/sprites/Symbols/Banana/Bananaicon16.png",
    slots1_17:  "/src/sprites/Symbols/Banana/Bananaicon17.png",
    slots1_18:  "/src/sprites/Symbols/Banana/Bananaicon18.png",
    slots1_19:  "/src/sprites/Symbols/Banana/Bananaicon19.png",
    slots1_20:  "/src/sprites/Symbols/Banana/Bananaicon20.png",


    slots2_0 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_1 :  "/src/sprites/Symbols/uncle/Uncleicon1.png",
    slots2_2 :  "/src/sprites/Symbols/uncle/Uncleicon2.png",
    slots2_3 :  "/src/sprites/Symbols/uncle/Uncleicon3.png",
    slots2_4 :  "/src/sprites/Symbols/uncle/Uncleicon4.png",
    slots2_5 :  "/src/sprites/Symbols/uncle/Uncleicon5.png",
    slots2_6 :  "/src/sprites/Symbols/uncle/Uncleicon6.png",
    slots2_7 :  "/src/sprites/Symbols/uncle/Uncleicon7.png",
    slots2_8 :  "/src/sprites/Symbols/uncle/Uncleicon8.png",
    slots2_9 :  "/src/sprites/Symbols/uncle/Uncleicon9.png",
    slots2_10:  "/src/sprites/Symbols/uncle/Uncleicon10.png",
    slots2_11:  "/src/sprites/Symbols/uncle/Uncleicon11.png",
    slots2_12:  "/src/sprites/Symbols/uncle/Uncleicon12.png",
    slots2_13:  "/src/sprites/Symbols/uncle/Uncleicon13.png",
    slots2_14:  "/src/sprites/Symbols/uncle/Uncleicon14.png",
    slots2_15:  "/src/sprites/Symbols/uncle/Uncleicon15.png",
    slots2_16:  "/src/sprites/Symbols/uncle/Uncleicon16.png",
    slots2_17:  "/src/sprites/Symbols/uncle/Uncleicon17.png",
    slots2_18:  "/src/sprites/Symbols/uncle/Uncleicon18.png",
    slots2_19:  "/src/sprites/Symbols/uncle/Uncleicon19.png",
    slots2_20:  "/src/sprites/Symbols/uncle/Uncleicon20.png",
    
    slots3_0 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_1 :  "/src/sprites/Symbols/bird/Birdicon1.png",
    slots3_2 :  "/src/sprites/Symbols/bird/Birdicon2.png",
    slots3_3 :  "/src/sprites/Symbols/bird/Birdicon3.png",
    slots3_4 :  "/src/sprites/Symbols/bird/Birdicon4.png",
    slots3_5 :  "/src/sprites/Symbols/bird/Birdicon5.png",
    slots3_6 :  "/src/sprites/Symbols/bird/Birdicon6.png",
    slots3_7 :  "/src/sprites/Symbols/bird/Birdicon7.png",
    slots3_8 :  "/src/sprites/Symbols/bird/Birdicon8.png",
    slots3_9 :  "/src/sprites/Symbols/bird/Birdicon9.png",
    slots3_10:  "/src/sprites/Symbols/bird/Birdicon10.png",
    slots3_11:  "/src/sprites/Symbols/bird/Birdicon11.png",
    slots3_12:  "/src/sprites/Symbols/bird/Birdicon12.png",
    slots3_13:  "/src/sprites/Symbols/bird/Birdicon13.png",
    slots3_14:  "/src/sprites/Symbols/bird/Birdicon14.png",
    slots3_15:  "/src/sprites/Symbols/bird/Birdicon15.png",
    slots3_16:  "/src/sprites/Symbols/bird/Birdicon16.png",
    slots3_17:  "/src/sprites/Symbols/bird/Birdicon17.png",
    slots3_18:  "/src/sprites/Symbols/bird/Birdicon18.png",
    slots3_19:  "/src/sprites/Symbols/bird/Birdicon19.png",
    slots3_20:  "/src/sprites/Symbols/bird/Birdicon20.png",

    slots4_0 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_1 :  "/src/sprites/Symbols/lion/Lionicon1.png",
    slots4_2 :  "/src/sprites/Symbols/lion/Lionicon2.png",
    slots4_3 :  "/src/sprites/Symbols/lion/Lionicon3.png",
    slots4_4 :  "/src/sprites/Symbols/lion/Lionicon4.png",
    slots4_5 :  "/src/sprites/Symbols/lion/Lionicon5.png",
    slots4_6 :  "/src/sprites/Symbols/lion/Lionicon6.png",
    slots4_7 :  "/src/sprites/Symbols/lion/Lionicon7.png",
    slots4_8 :  "/src/sprites/Symbols/lion/Lionicon8.png",
    slots4_9 :  "/src/sprites/Symbols/lion/Lionicon9.png",
    slots4_10:  "/src/sprites/Symbols/lion/Lionicon10.png",
    slots4_11:  "/src/sprites/Symbols/lion/Lionicon11.png",
    slots4_12:  "/src/sprites/Symbols/lion/Lionicon12.png",
    slots4_13:  "/src/sprites/Symbols/lion/Lionicon13.png",
    slots4_14:  "/src/sprites/Symbols/lion/Lionicon14.png",
    slots4_15:  "/src/sprites/Symbols/lion/Lionicon15.png",
    slots4_16:  "/src/sprites/Symbols/lion/Lionicon16.png",
    slots4_17:  "/src/sprites/Symbols/lion/Lionicon17.png",
    slots4_18:  "/src/sprites/Symbols/lion/Lionicon18.png",
    slots4_19:  "/src/sprites/Symbols/lion/Lionicon19.png",
    slots4_20:  "/src/sprites/Symbols/lion/Lionicon20.png",

    slots5_0 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_1 :  "/src/sprites/Symbols/rhino/Rhinoicon1.png",
    slots5_2 :  "/src/sprites/Symbols/rhino/Rhinoicon2.png",
    slots5_3 :  "/src/sprites/Symbols/rhino/Rhinoicon3.png",
    slots5_4 :  "/src/sprites/Symbols/rhino/Rhinoicon4.png",
    slots5_5 :  "/src/sprites/Symbols/rhino/Rhinoicon5.png",
    slots5_6 :  "/src/sprites/Symbols/rhino/Rhinoicon6.png",
    slots5_7 :  "/src/sprites/Symbols/rhino/Rhinoicon7.png",
    slots5_8 :  "/src/sprites/Symbols/rhino/Rhinoicon8.png",
    slots5_9 :  "/src/sprites/Symbols/rhino/Rhinoicon9.png",
    slots5_10:  "/src/sprites/Symbols/rhino/Rhinoicon10.png",
    slots5_11:  "/src/sprites/Symbols/rhino/Rhinoicon11.png",
    slots5_12:  "/src/sprites/Symbols/rhino/Rhinoicon12.png",
    slots5_13:  "/src/sprites/Symbols/rhino/Rhinoicon13.png",
    slots5_14:  "/src/sprites/Symbols/rhino/Rhinoicon14.png",
    slots5_15:  "/src/sprites/Symbols/rhino/Rhinoicon15.png",
    slots5_16:  "/src/sprites/Symbols/rhino/Rhinoicon16.png",
    slots5_17:  "/src/sprites/Symbols/rhino/Rhinoicon17.png",
    slots5_18:  "/src/sprites/Symbols/rhino/Rhinoicon18.png",
    slots5_19:  "/src/sprites/Symbols/rhino/Rhinoicon19.png",
    slots5_20:  "/src/sprites/Symbols/rhino/Rhinoicon20.png",


    slots6_0 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_1 :  "/src/sprites/Symbols/crocodile/Crocodileicon1.png",
    slots6_2 :  "/src/sprites/Symbols/crocodile/Crocodileicon2.png",
    slots6_3 :  "/src/sprites/Symbols/crocodile/Crocodileicon3.png",
    slots6_4 :  "/src/sprites/Symbols/crocodile/Crocodileicon4.png",
    slots6_5 :  "/src/sprites/Symbols/crocodile/Crocodileicon5.png",
    slots6_6 :  "/src/sprites/Symbols/crocodile/Crocodileicon6.png",
    slots6_7 :  "/src/sprites/Symbols/crocodile/Crocodileicon7.png",
    slots6_8 :  "/src/sprites/Symbols/crocodile/Crocodileicon8.png",
    slots6_9 :  "/src/sprites/Symbols/crocodile/Crocodileicon9.png",
    slots6_10:  "/src/sprites/Symbols/crocodile/Crocodileicon10.png",
    slots6_11:  "/src/sprites/Symbols/crocodile/Crocodileicon11.png",
    slots6_12:  "/src/sprites/Symbols/crocodile/Crocodileicon12.png",
    slots6_13:  "/src/sprites/Symbols/crocodile/Crocodileicon13.png",
    slots6_14:  "/src/sprites/Symbols/crocodile/Crocodileicon14.png",
    slots6_15:  "/src/sprites/Symbols/crocodile/Crocodileicon15.png",
    slots6_16:  "/src/sprites/Symbols/crocodile/Crocodileicon16.png",
    slots6_17:  "/src/sprites/Symbols/crocodile/Crocodileicon17.png",
    slots6_18:  "/src/sprites/Symbols/crocodile/Crocodileicon18.png",
    slots6_19:  "/src/sprites/Symbols/crocodile/Crocodileicon19.png",
    slots6_20:  "/src/sprites/Symbols/crocodile/Crocodileicon20.png",


    slots7_0 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_1 :  "/src/sprites/Symbols/coconut/Cocouticon1.png",
    slots7_2 :  "/src/sprites/Symbols/coconut/Cocouticon2.png",
    slots7_3 :  "/src/sprites/Symbols/coconut/Cocouticon3.png",
    slots7_4 :  "/src/sprites/Symbols/coconut/Cocouticon4.png",
    slots7_5 :  "/src/sprites/Symbols/coconut/Cocouticon5.png",
    slots7_6 :  "/src/sprites/Symbols/coconut/Cocouticon6.png",
    slots7_7 :  "/src/sprites/Symbols/coconut/Cocouticon7.png",
    slots7_8 :  "/src/sprites/Symbols/coconut/Cocouticon8.png",
    slots7_9 :  "/src/sprites/Symbols/coconut/Cocouticon9.png",
    slots7_10:  "/src/sprites/Symbols/coconut/Cocouticon10.png",
    slots7_11:  "/src/sprites/Symbols/coconut/Cocouticon11.png",
    slots7_12:  "/src/sprites/Symbols/coconut/Cocouticon12.png",
    slots7_13:  "/src/sprites/Symbols/coconut/Cocouticon13.png",
    slots7_14:  "/src/sprites/Symbols/coconut/Cocouticon14.png",
    slots7_15:  "/src/sprites/Symbols/coconut/Cocouticon15.png",
    slots7_16:  "/src/sprites/Symbols/coconut/Cocouticon16.png",
    slots7_17:  "/src/sprites/Symbols/coconut/Cocouticon17.png",
    slots7_18:  "/src/sprites/Symbols/coconut/Cocouticon18.png",
    slots7_19:  "/src/sprites/Symbols/coconut/Cocouticon19.png",
    slots7_20:  "/src/sprites/Symbols/coconut/Cocouticon20.png",


    slots8_0 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_1 :  "/src/sprites/Symbols/bonus/Bonusicon1.png",
    slots8_2 :  "/src/sprites/Symbols/bonus/Bonusicon2.png",
    slots8_3 :  "/src/sprites/Symbols/bonus/Bonusicon3.png",
    slots8_4 :  "/src/sprites/Symbols/bonus/Bonusicon4.png",
    slots8_5 :  "/src/sprites/Symbols/bonus/Bonusicon5.png",
    slots8_6 :  "/src/sprites/Symbols/bonus/Bonusicon6.png",
    slots8_7 :  "/src/sprites/Symbols/bonus/Bonusicon7.png",
    slots8_8 :  "/src/sprites/Symbols/bonus/Bonusicon8.png",
    slots8_9 :  "/src/sprites/Symbols/bonus/Bonusicon9.png",
    slots8_10:  "/src/sprites/Symbols/bonus/Bonusicon10.png",
    slots8_11:  "/src/sprites/Symbols/bonus/Bonusicon11.png",
    slots8_12:  "/src/sprites/Symbols/bonus/Bonusicon12.png",
    slots8_13:  "/src/sprites/Symbols/bonus/Bonusicon13.png",
    slots8_14:  "/src/sprites/Symbols/bonus/Bonusicon14.png",
    slots8_15:  "/src/sprites/Symbols/bonus/Bonusicon15.png",
    slots8_16:  "/src/sprites/Symbols/bonus/Bonusicon16.png",
    slots8_17:  "/src/sprites/Symbols/bonus/Bonusicon17.png",
    slots8_18:  "/src/sprites/Symbols/bonus/Bonusicon18.png",
    slots8_19:  "/src/sprites/Symbols/bonus/Bonusicon19.png",
    slots8_20:  "/src/sprites/Symbols/bonus/Bonusicon20.png",
    slots8_21:  "/src/sprites/Symbols/bonus/Bonusicon21.png",
    slots8_22:  "/src/sprites/Symbols/bonus/Bonusicon22.png",
    slots8_23:  "/src/sprites/Symbols/bonus/Bonusicon23.png",
    slots8_24:  "/src/sprites/Symbols/bonus/Bonusicon24.png",
    slots8_25:  "/src/sprites/Symbols/bonus/Bonusicon25.png",

    slots9_0 :  "/src/sprites/Symbols/wild/wildicon00.png",
    slots9_1 :  "/src/sprites/Symbols/wild/wildicon01.png",
    slots9_2 :  "/src/sprites/Symbols/wild/wildicon02.png",
    slots9_3 :  "/src/sprites/Symbols/wild/wildicon03.png",
    slots9_4 :  "/src/sprites/Symbols/wild/wildicon04.png",
    slots9_5 :  "/src/sprites/Symbols/wild/wildicon05.png",
    slots9_6 :  "/src/sprites/Symbols/wild/wildicon06.png",
    slots9_7 :  "/src/sprites/Symbols/wild/wildicon07.png",
    slots9_8 :  "/src/sprites/Symbols/wild/wildicon08.png",
    slots9_9 :  "/src/sprites/Symbols/wild/wildicon09.png",
    slots9_10:  "/src/sprites/Symbols/wild/wildicon10.png",
    slots9_11:  "/src/sprites/Symbols/wild/wildicon11.png",
    slots9_12:  "/src/sprites/Symbols/wild/wildicon12.png",
    slots9_13:  "/src/sprites/Symbols/wild/wildicon13.png",
    slots9_14:  "/src/sprites/Symbols/wild/wildicon14.png",
    slots9_15:  "/src/sprites/Symbols/wild/wildicon15.png",
    slots9_16:  "/src/sprites/Symbols/wild/wildicon16.png",
    slots9_17:  "/src/sprites/Symbols/wild/wildicon17.png",
    slots9_18:  "/src/sprites/Symbols/wild/wildicon18.png",
    slots9_19:  "/src/sprites/Symbols/wild/wildicon19.png",
   
    
    monkeyanim0: "src/sprites/HangingMonkey/monkeyanim1.png",
    monkeyanim1: "src/sprites/HangingMonkey/monkeyanim2.png",
    monkeyanim2: "src/sprites/HangingMonkey/monkeyanim3.png",
    monkeyanim3: "src/sprites/HangingMonkey/monkeyanim4.png",
    monkeyanim4: "src/sprites/HangingMonkey/monkeyanim5.png",
    monkeyanim5: "src/sprites/HangingMonkey/monkeyanim6.png",
    monkeyanim6: "src/sprites/HangingMonkey/monkeyanim7.png",
    monkeyanim7: "src/sprites/HangingMonkey/monkeyanim8.png",
    monkeyanim8: "src/sprites/HangingMonkey/monkeyanim9.png",
    monkeyanim9: "src/sprites/HangingMonkey/monkeyanim10.png",
    monkeyanim10: "src/sprites/HangingMonkey/monkeyanim11.png",
    monkeyanim11: "src/sprites/HangingMonkey/monkeyanim12.png",
    monkeyanim12: "src/sprites/HangingMonkey/monkeyanim13.png",
    monkeyanim13: "src/sprites/HangingMonkey/monkeyanim14.png",
    monkeyanim14: "src/sprites/HangingMonkey/monkeyanim15.png",
    monkeyanim15: "src/sprites/HangingMonkey/monkeyanim16.png",
    monkeyanim16: "src/sprites/HangingMonkey/monkeyanim17.png",
    monkeyanim17: "src/sprites/HangingMonkey/monkeyanim18.png",
    monkeyanim18: "src/sprites/HangingMonkey/monkeyanim19.png",
    monkeyanim19: "src/sprites/HangingMonkey/monkeyanim20.png",
    monkeyanim20: "src/sprites/HangingMonkey/monkeyanim21.png",
    monkeyanim21: "src/sprites/HangingMonkey/monkeyanim22.png",
    monkeyanim22: "src/sprites/HangingMonkey/monkeyanim23.png",
    monkeyanim23: "src/sprites/HangingMonkey/monkeyanim24.png",
    monkeyanim24: "src/sprites/HangingMonkey/monkeyanim25.png",
    monkeyanim25: "src/sprites/HangingMonkey/monkeyanim26.png",
    monkeyanim26: "src/sprites/HangingMonkey/monkeyanim27.png",
    monkeyanim27: "src/sprites/HangingMonkey/monkeyanim28.png",
    monkeyanim28: "src/sprites/HangingMonkey/monkeyanim29.png",
    monkeyanim29: "src/sprites/HangingMonkey/monkeyanim30.png",
    monkeyanim30: "src/sprites/HangingMonkey/monkeyanim31.png",
    monkeyanim31: "src/sprites/HangingMonkey/monkeyanim32.png",
    monkeyanim32: "src/sprites/HangingMonkey/monkeyanim33.png",
    monkeyanim33: "src/sprites/HangingMonkey/monkeyanim34.png",
    monkeyanim34: "src/sprites/HangingMonkey/monkeyanim35.png",
    monkeyanim35: "src/sprites/HangingMonkey/monkeyanim36.png",
    monkeyanim36: "src/sprites/HangingMonkey/monkeyanim37.png",
    monkeyanim37: "src/sprites/HangingMonkey/monkeyanim38.png",
    monkeyanim38: "src/sprites/HangingMonkey/monkeyanim39.png",
    monkeyanim39: "src/sprites/HangingMonkey/monkeyanim40.png",
    
    turboAnim0: "src/sprites/turboBtn0.png",
    turboAnim1: "src/sprites/turboBtn1.png",
    turboAnim2: "src/sprites/turboBtn2.png",
    turboAnim3: "src/sprites/turboBtn3.png",
    turboAnim4: "src/sprites/turboBtn4.png",
    turboAnim5: "src/sprites/turboBtn5.png",
    turboAnim6: "src/sprites/turboBtn6.png",
    turboAnim7: "src/sprites/turboBtn7.png",
    turboAnim8: "src/sprites/turboBtn8.png",
    turboAnim9: "src/sprites/turboBtn9.png",
    turboAnim10: "src/sprites/turboBtn10.png",
    turboAnim11: "src/sprites/turboBtn11.png",
    turboAnim12: "src/sprites/turboBtn12.png",
    turboAnim13: "src/sprites/turboBtn13.png",
    turboAnim14: "src/sprites/turboBtn14.png",
    turboAnim15: "src/sprites/turboBtn15.png",
    turboAnim16: "src/sprites/turboBtn16.png",
    turboAnim17: "src/sprites/turboBtn17.png",
    turboAnim18: "src/sprites/turboBtn18.png",
    turboAnim19: "src/sprites/turboBtn19.png",
    turboAnim20: "src/sprites/turboBtn20.png",
    turboAnim21: "src/sprites/turboBtn21.png",
    turboAnim22: "src/sprites/turboBtn22.png",
    turboAnim23: "src/sprites/turboBtn23.png",                          
    turboAnim24: "src/sprites/turboBtn24.png",
    turboAnim25: "src/sprites/turboBtn25.png",
    turboAnim26: "src/sprites/turboBtn26.png",                                      
    turboAnim27: "src/sprites/turboBtn27.png",
    turboAnim28: "src/sprites/turboBtn28.png",
    turboAnim29: "src/sprites/turboBtn29.png",
    turboAnim30: "src/sprites/turboBtn30.png",
    turboAnim31: "src/sprites/turboBtn31.png",
    turboAnim32: "src/sprites/turboBtn32.png",
    turboAnim33: "src/sprites/turboBtn33.png",
    turboAnim34: "src/sprites/turboBtn34.png",
    turboAnim35: "src/sprites/turboBtn35.png",
    turboAnim36: "src/sprites/turboBtn36.png",
    turboAnim37: "src/sprites/turboBtn37.png",
    turboAnim38: "src/sprites/turboBtn38.png",
    turboAnim39: "src/sprites/turboBtn39.png",
    //
    stopButton: "src/sprites/stopButton.png",
    
}



export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = ["Montserrat"];



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.mp3",
        spinWheelMusic: "src/sounds/spinWheel.mp3",
        bonusBg: "src/sounds/bonusbg.wav",
        bonuswin: "src/sounds/bonuswin.wav",
        cardMusic: "src/sounds/card.mp3",
        coconutFall: "src/sounds/coconutfall.wav"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}