// import { Background } from './Background';
export const LoaderConfig = {
    // frame : "/src/sprites/SlotMachine_3x5.png",
    gameBg: "src/sprites/GameBackground.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed :  "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",    
    balancePanel :  "/src/sprites/PanelBalance.png",
    // fireVase :  "/src/sprites/Vase.png",
    // PanelJackpot :  "/src/sprites/PanelJackpot.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    rulesBtn :  "/src/sprites/ButtonRules.png",
    rulesBtnH :  "/src/sprites/ButtonRulesHover.png",
    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    popupBgimg: "src/sprites/AboutPanel.png",
    messagePopup: "src/sprites/messagepopup.png",
    normalButton: "src/sprites/NormalButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinpopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    freeSpinStartButton: "src/sprites/freeSpinStartButton.png",
    freeSpinStartButtonPressed: "src/sprites/SpinButtonPressed.png",
    spinCircle: "src/sprites/SpinCircle.png",
    spinCenter: "src/sprites/SpinCenter.png",
    wheelBg: "src/sprites/WheelBg.png",

    logo: "src/sprites/crazyMonkeyLogo.png",
    loadingText:"src/sprite/loadingText.png",
    assetsloader: "src/sprites/assetsLoader.png",
    loaderBg: "src/sprites/loaderBg.png",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    roof:"src/sprites/Roof.png",
    winLine: "src/sprites/WinLine.png",
    // lineSymbols: "src/sprites/LineSymbols.png",
    settingPopup:"src/sprites/settingPopup.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    toggleBar: "src/sprites/ToggleBar.png",
    onButton: "src/sprites/On.png",
    offButton: "src/sprites/Off.png",
    headingImage: "src/sprites/PayTable_.png",
    popupbg: "src/sprites/PopupBg.jpg",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",

    left0: "src/sprites/Colorfulleft1.png",
    left1: "src/sprites/Colorfulleft2.png",
    left2: "src/sprites/Colorfulleft3.png",
    left3: "src/sprites/Colorfulleft4.png",
    left4: "src/sprites/Colorfulleft5.png",
    left5: "src/sprites/Colorfulleft6.png",
    left6: "src/sprites/Colorfulleft7.png",
    left7: "src/sprites/Colorfulleft8.png",
    left8: "src/sprites/Colorfulleft9.png",


    leftHover0: "src/sprites/Blackleft1.png",
    leftHover1: "src/sprites/Blackleft2.png",
    leftHover2: "src/sprites/Blackleft3.png",
    leftHover3: "src/sprites/Blackleft4.png",
    leftHover4: "src/sprites/Blackleft5.png",
    leftHover5: "src/sprites/Blackleft6.png",
    leftHover6: "src/sprites/Blackleft7.png",
    leftHover7: "src/sprites/Blackleft8.png",
    leftHover8: "src/sprites/Blackleft9.png",

    right0: "src/sprites/Colorfulright1.png",
    right1: "src/sprites/Colorfulright2.png",
    right2: "src/sprites/Colorfulright3.png",
    right3: "src/sprites/Colorfulright4.png",
    right4: "src/sprites/Colorfulright5.png",
    right5: "src/sprites/Colorfulright6.png",
    right6: "src/sprites/Colorfulright7.png",
    right7: "src/sprites/Colorfulright8.png",
    right8: "src/sprites/Colorfulright9.png",

    rightHover0: "src/sprites/Blackright1.png",
    rightHover1: "src/sprites/Blackright2.png",
    rightHover2: "src/sprites/Blackright3.png",
    rightHover3: "src/sprites/Blackright4.png",
    rightHover4: "src/sprites/Blackright5.png",
    rightHover5: "src/sprites/Blackright6.png",
    rightHover6: "src/sprites/Blackright7.png",
    rightHover7: "src/sprites/Blackright8.png",
    rightHover8: "src/sprites/Blackright9.png",
    
    slots0_0 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_1 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_2 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_3 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_4 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_5 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_6 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_7 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_8 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_9 :  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_10:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_11:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_12:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_13:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_14:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_15:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_16:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_17:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_18:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_19:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_20:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_21:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_22:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",
    slots0_23:  "/src/sprites/Symbols/Monkey/Monkeyicon.png",

    slots1_0 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_1 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_2 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_3 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_4 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_5 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_6 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_7 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_8 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_9 :  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_10:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_11:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_12:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_13:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_14:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_15:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_16:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_17:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_18:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_19:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_20:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_21:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_22:  "/src/sprites/Symbols/Banana/Bananaicon.png",
    slots1_23:  "/src/sprites/Symbols/Banana/Bananaicon.png",

    slots2_0 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_1 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_2 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_3 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_4 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_5 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_6 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_7 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_8 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_9 :  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_10:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_11:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_12:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_13:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_14:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_15:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_16:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_17:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_18:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_19:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_20:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_21:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_22:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    slots2_23:  "/src/sprites/Symbols/uncle/Uncleicon.png",
    
    slots3_0 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_1 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_2 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_3 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_4 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_5 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_6 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_7 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_8 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_9 :  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_10:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_11:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_12:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_13:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_14:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_15:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_16:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_17:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_18:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_19:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_20:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_21:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_22:  "/src/sprites/Symbols/bird/Birdicon.png",
    slots3_23:  "/src/sprites/Symbols/bird/Birdicon.png",

    slots4_0 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_1 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_2 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_3 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_4 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_5 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_6 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_7 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_8 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_9 :  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_10:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_11:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_12:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_13:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_14:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_15:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_16:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_17:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_18:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_19:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_20:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_21:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_22:  "/src/sprites/Symbols/lion/Lionicon.png",
    slots4_23:  "/src/sprites/Symbols/lion/Lionicon.png",

    slots5_0 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_1 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_2 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_3 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_4 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_5 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_6 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_7 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_8 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_9 :  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_10:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_11:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_12:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_13:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_14:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_15:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_16:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_17:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_18:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_19:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_20:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_21:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_22:  "/src/sprites/Symbols/rhino/Rhinoicon.png",
    slots5_23:  "/src/sprites/Symbols/rhino/Rhinoicon.png",

    slots6_0 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_1 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_2 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_3 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_4 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_5 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_6 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_7 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_8 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_9 :  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_10:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_11:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_12:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_13:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_14:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_15:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_16:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_17:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_18:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_19:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_20:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_21:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_22:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",
    slots6_23:  "/src/sprites/Symbols/crocodile/Crocodileicon.png",

    slots7_0 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_1 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_2 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_3 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_4 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_5 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_6 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_7 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_8 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_9 :  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_10:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_11:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_12:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_13:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_14:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_15:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_16:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_17:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_18:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_19:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_20:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_21:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_22:  "/src/sprites/Symbols/coconut/Cocouticon.png",
    slots7_23:  "/src/sprites/Symbols/coconut/Cocouticon.png",

    slots8_0 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_1 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_2 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_3 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_4 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_5 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_6 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_7 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_8 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_9 :  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_10:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_11:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_12:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_13:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_14:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_15:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_16:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_17:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_18:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_19:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_20:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_21:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_22:  "/src/sprites/Symbols/bonus/Bonusicon.png",
    slots8_23:  "/src/sprites/Symbols/bonus/Bonusicon.png",

    // slots9_0 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 01.png",
    // slots9_1 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 02.png",
    // slots9_2 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 03.png",
    // slots9_3 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 04.png",
    // slots9_4 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 05.png",
    // slots9_5 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 06.png",
    // slots9_6 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 07.png",
    // slots9_7 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 08.png",
    // slots9_8 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 09.png",
    // slots9_9 :  "/src/sprites/Symbols/FreeSpins/FreeSpins 10.png",
    // slots9_10:  "/src/sprites/Symbols/FreeSpins/FreeSpins 11.png",
    // slots9_11:  "/src/sprites/Symbols/FreeSpins/FreeSpins 12.png",
    // slots9_12:  "/src/sprites/Symbols/FreeSpins/FreeSpins 13.png",
    // slots9_13:  "/src/sprites/Symbols/FreeSpins/FreeSpins 14.png",
    // slots9_14:  "/src/sprites/Symbols/FreeSpins/FreeSpins 15.png",
    // slots9_15:  "/src/sprites/Symbols/FreeSpins/FreeSpins 16.png",
    // slots9_16:  "/src/sprites/Symbols/FreeSpins/FreeSpins 17.png",
    // slots9_17:  "/src/sprites/Symbols/FreeSpins/FreeSpins 18.png",
    // slots9_18:  "/src/sprites/Symbols/FreeSpins/FreeSpins 19.png",
    // slots9_19:  "/src/sprites/Symbols/FreeSpins/FreeSpins 20.png",
    // slots9_20:  "/src/sprites/Symbols/FreeSpins/FreeSpins 21.png",
    // slots9_21:  "/src/sprites/Symbols/FreeSpins/FreeSpins 22.png",
    // slots9_22:  "/src/sprites/Symbols/FreeSpins/FreeSpins 23.png",
    // slots9_23:  "/src/sprites/Symbols/FreeSpins/FreeSpins 24.png",
    // slots9_24:  "/src/sprites/Symbols/FreeSpins/FreeSpins 25.png",
    // slots9_25:  "/src/sprites/Symbols/FreeSpins/FreeSpins 26.png",
    // slots9_26:  "/src/sprites/Symbols/FreeSpins/FreeSpins 27.png",
    // slots9_27:  "/src/sprites/Symbols/FreeSpins/FreeSpins 28.png",
    // slots9_28:  "/src/sprites/Symbols/FreeSpins/FreeSpins 29.png",
    // slots9_29:  "/src/sprites/Symbols/FreeSpins/FreeSpins 30.png",
    // slots9_30:  "/src/sprites/Symbols/FreeSpins/FreeSpins 31.png",
    // slots9_31:  "/src/sprites/Symbols/FreeSpins/FreeSpins 32.png",
    // slots9_32:  "/src/sprites/Symbols/FreeSpins/FreeSpins 33.png",
    // slots9_33:  "/src/sprites/Symbols/FreeSpins/FreeSpins 34.png",
    // slots9_34:  "/src/sprites/Symbols/FreeSpins/FreeSpins 35.png",
    // slots9_35:  "/src/sprites/Symbols/FreeSpins/FreeSpins 36.png",


    // slots10_0 :  "/src/sprites/Symbols/Wild/Wild 01.png",
    // slots10_1 :  "/src/sprites/Symbols/Wild/Wild 02.png",
    // slots10_2 :  "/src/sprites/Symbols/Wild/Wild 03.png",
    // slots10_3 :  "/src/sprites/Symbols/Wild/Wild 04.png",
    // slots10_4 :  "/src/sprites/Symbols/Wild/Wild 05.png",
    // slots10_5 :  "/src/sprites/Symbols/Wild/Wild 06.png",
    // slots10_6 :  "/src/sprites/Symbols/Wild/Wild 07.png",
    // slots10_7 :  "/src/sprites/Symbols/Wild/Wild 08.png",
    // slots10_8 :  "/src/sprites/Symbols/Wild/Wild 09.png",
    // slots10_9 :  "/src/sprites/Symbols/Wild/Wild 10.png",
    // slots10_10:  "/src/sprites/Symbols/Wild/Wild 11.png",
    // slots10_11:  "/src/sprites/Symbols/Wild/Wild 12.png",
    // slots10_12:  "/src/sprites/Symbols/Wild/Wild 13.png",
    // slots10_13:  "/src/sprites/Symbols/Wild/Wild 14.png",
    // slots10_14:  "/src/sprites/Symbols/Wild/Wild 15.png",
    // slots10_15:  "/src/sprites/Symbols/Wild/Wild 16.png",
    // slots10_16:  "/src/sprites/Symbols/Wild/Wild 17.png",
    // slots10_17:  "/src/sprites/Symbols/Wild/Wild 18.png",
    // slots10_18:  "/src/sprites/Symbols/Wild/Wild 19.png",
    // slots10_19:  "/src/sprites/Symbols/Wild/Wild 20.png",
    // slots10_20:  "/src/sprites/Symbols/Wild/Wild 21.png",
    // slots10_21:  "/src/sprites/Symbols/Wild/Wild 22.png",
    // slots10_22:  "/src/sprites/Symbols/Wild/Wild 23.png",
    // slots10_23:  "/src/sprites/Symbols/Wild/Wild 24.png",
    // slots10_24:  "/src/sprites/Symbols/Wild/Wild 25.png",
    // slots10_25:  "/src/sprites/Symbols/Wild/Wild 26.png",
    // slots10_26:  "/src/sprites/Symbols/Wild/Wild 27.png",
    // slots10_27:  "/src/sprites/Symbols/Wild/Wild 28.png",
    // slots10_28:  "/src/sprites/Symbols/Wild/Wild 29.png",
    // slots10_29:  "/src/sprites/Symbols/Wild/Wild 30.png",
    // slots10_30:  "/src/sprites/Symbols/Wild/Wild 31.png",
    // slots10_31:  "/src/sprites/Symbols/Wild/Wild 32.png",
    // slots10_32:  "/src/sprites/Symbols/Wild/Wild 33.png",
    // slots10_33:  "/src/sprites/Symbols/Wild/Wild 34.png",
    // slots10_34:  "/src/sprites/Symbols/Wild/Wild 35.png",
    // slots10_35:  "/src/sprites/Symbols/Wild/Wild 36.png",

    // slots9_0 :  "/src/sprites/Symbols/Wick/Wick (1).png",
    // slots9_1 :  "/src/sprites/Symbols/Wick/Wick (2).png",
    // slots9_2 :  "/src/sprites/Symbols/Wick/Wick (3).png",
    // slots9_3 :  "/src/sprites/Symbols/Wick/Wick (4).png",
    // slots9_4 :  "/src/sprites/Symbols/Wick/Wick (5).png",
    // slots9_5 :  "/src/sprites/Symbols/Wick/Wick (6).png",
    // slots9_6 :  "/src/sprites/Symbols/Wick/Wick (7).png",
    // slots9_7 :  "/src/sprites/Symbols/Wick/Wick (8).png",
    // slots9_8 :  "/src/sprites/Symbols/Wick/Wick (9).png",
    // slots9_9 :  "/src/sprites/Symbols/Wick/Wick (10).png",
    // slots9_10:  "/src/sprites/Symbols/Wick/Wick (11).png",
    // slots9_11:  "/src/sprites/Symbols/Wick/Wick (12).png",
    // slots9_12:  "/src/sprites/Symbols/Wick/Wick (13).png",
    // slots9_13:  "/src/sprites/Symbols/Wick/Wick (14).png",
    // slots9_14:  "/src/sprites/Symbols/Wick/Wick (15).png",
    // slots9_15:  "/src/sprites/Symbols/Wick/Wick (16).png",
    // slots9_16:  "/src/sprites/Symbols/Wick/Wick (17).png",
    // slots9_17:  "/src/sprites/Symbols/Wick/Wick (18).png",
    // slots9_18:  "/src/sprites/Symbols/Wick/Wick (19).png",
    // slots9_19:  "/src/sprites/Symbols/Wick/Wick (20).png",
    // slots9_20:  "/src/sprites/Symbols/Wick/Wick (21).png",
    // slots9_21:  "/src/sprites/Symbols/Wick/Wick (22).png",
    // slots9_22:  "/src/sprites/Symbols/Wick/Wick (23).png",
    // slots9_23:  "/src/sprites/Symbols/Wick/Wick (24).png",

    // slots11_0 :  "/src/sprites/Symbols/Scatter/Scatter 01.png",
    // slots11_1 :  "/src/sprites/Symbols/Scatter/Scatter 02.png",
    // slots11_2 :  "/src/sprites/Symbols/Scatter/Scatter 03.png",
    // slots11_3 :  "/src/sprites/Symbols/Scatter/Scatter 04.png",
    // slots11_4 :  "/src/sprites/Symbols/Scatter/Scatter 05.png",
    // slots11_5 :  "/src/sprites/Symbols/Scatter/Scatter 06.png",
    // slots11_6 :  "/src/sprites/Symbols/Scatter/Scatter 07.png",
    // slots11_7 :  "/src/sprites/Symbols/Scatter/Scatter 08.png",
    // slots11_8 :  "/src/sprites/Symbols/Scatter/Scatter 09.png",
    // slots11_9 :  "/src/sprites/Symbols/Scatter/Scatter 10.png",
    // slots11_10:  "/src/sprites/Symbols/Scatter/Scatter 11.png",
    // slots11_11:  "/src/sprites/Symbols/Scatter/Scatter 12.png",
    // slots11_12:  "/src/sprites/Symbols/Scatter/Scatter 13.png",
    // slots11_13:  "/src/sprites/Symbols/Scatter/Scatter 14.png",
    // slots11_14:  "/src/sprites/Symbols/Scatter/Scatter 15.png",
    // slots11_15:  "/src/sprites/Symbols/Scatter/Scatter 16.png",
    // slots11_16:  "/src/sprites/Symbols/Scatter/Scatter 17.png",
    // slots11_17:  "/src/sprites/Symbols/Scatter/Scatter 18.png",
    // slots11_18:  "/src/sprites/Symbols/Scatter/Scatter 19.png",
    // slots11_19:  "/src/sprites/Symbols/Scatter/Scatter 20.png",
    // slots11_20:  "/src/sprites/Symbols/Scatter/Scatter 21.png",
    // slots11_21:  "/src/sprites/Symbols/Scatter/Scatter 22.png",
    // slots11_22:  "/src/sprites/Symbols/Scatter/Scatter 23.png",
    // slots11_23:  "/src/sprites/Symbols/Scatter/Scatter 24.png",
    // slots11_24:  "/src/sprites/Symbols/Scatter/Scatter 25.png",
    // slots11_25:  "/src/sprites/Symbols/Scatter/Scatter 26.png",
    // slots11_26:  "/src/sprites/Symbols/Scatter/Scatter 27.png",
    // slots11_27:  "/src/sprites/Symbols/Scatter/Scatter 28.png",
    // slots11_28:  "/src/sprites/Symbols/Scatter/Scatter 29.png",
    // slots11_29:  "/src/sprites/Symbols/Scatter/Scatter 30.png",
    // slots11_30:  "/src/sprites/Symbols/Scatter/Scatter 31.png",
    // slots11_31:  "/src/sprites/Symbols/Scatter/Scatter 32.png",
    // slots11_32:  "/src/sprites/Symbols/Scatter/Scatter 33.png",
    // slots11_33:  "/src/sprites/Symbols/Scatter/Scatter 34.png",
    // slots11_34:  "/src/sprites/Symbols/Scatter/Scatter 35.png",
    // slots11_35:  "/src/sprites/Symbols/Scatter/Scatter 36.png",   

    // slots12_0 :  "/src/sprites/Symbols/Jackpot/Jackpot 01.png",
    // slots12_1 :  "/src/sprites/Symbols/Jackpot/Jackpot 02.png",
    // slots12_2 :  "/src/sprites/Symbols/Jackpot/Jackpot 03.png",
    // slots12_3 :  "/src/sprites/Symbols/Jackpot/Jackpot 04.png",
    // slots12_4 :  "/src/sprites/Symbols/Jackpot/Jackpot 05.png",
    // slots12_5 :  "/src/sprites/Symbols/Jackpot/Jackpot 06.png",
    // slots12_6 :  "/src/sprites/Symbols/Jackpot/Jackpot 07.png",
    // slots12_7 :  "/src/sprites/Symbols/Jackpot/Jackpot 08.png",
    // slots12_8 :  "/src/sprites/Symbols/Jackpot/Jackpot 09.png",
    // slots12_9 :  "/src/sprites/Symbols/Jackpot/Jackpot 10.png",
    // slots12_10:  "/src/sprites/Symbols/Jackpot/Jackpot 11.png",
    // slots12_11:  "/src/sprites/Symbols/Jackpot/Jackpot 12.png",
    // slots12_12:  "/src/sprites/Symbols/Jackpot/Jackpot 13.png",
    // slots12_13:  "/src/sprites/Symbols/Jackpot/Jackpot 14.png",
    // slots12_14:  "/src/sprites/Symbols/Jackpot/Jackpot 15.png",
    // slots12_15:  "/src/sprites/Symbols/Jackpot/Jackpot 16.png",
    // slots12_16:  "/src/sprites/Symbols/Jackpot/Jackpot 17.png",
    // slots12_17:  "/src/sprites/Symbols/Jackpot/Jackpot 18.png",
    // slots12_18:  "/src/sprites/Symbols/Jackpot/Jackpot 19.png",
    // slots12_19:  "/src/sprites/Symbols/Jackpot/Jackpot 20.png",
    // slots12_20:  "/src/sprites/Symbols/Jackpot/Jackpot 21.png",
    // slots12_21:  "/src/sprites/Symbols/Jackpot/Jackpot 22.png",
    // slots12_22:  "/src/sprites/Symbols/Jackpot/Jackpot 23.png",
    // slots12_23:  "/src/sprites/Symbols/Jackpot/Jackpot 24.png",
    // slots12_24:  "/src/sprites/Symbols/Jackpot/Jackpot 25.png",
    // slots12_25:  "/src/sprites/Symbols/Jackpot/Jackpot 26.png",
    // slots12_26:  "/src/sprites/Symbols/Jackpot/Jackpot 27.png",
    // slots12_27:  "/src/sprites/Symbols/Jackpot/Jackpot 28.png",
    // slots12_28:  "/src/sprites/Symbols/Jackpot/Jackpot 29.png",
    // slots12_29:  "/src/sprites/Symbols/Jackpot/Jackpot 30.png",
    // slots12_30:  "/src/sprites/Symbols/Jackpot/Jackpot 31.png",
    // slots12_31:  "/src/sprites/Symbols/Jackpot/Jackpot 32.png",
    // slots12_32:  "/src/sprites/Symbols/Jackpot/Jackpot 33.png",
    // slots12_33:  "/src/sprites/Symbols/Jackpot/Jackpot 34.png",
    // slots12_34:  "/src/sprites/Symbols/Jackpot/Jackpot 35.png",
    // slots12_35:  "/src/sprites/Symbols/Jackpot/Jackpot 36.png",

    // slots13_0 :  "/src/sprites/Symbols/Bonus/Bonus 01.png",
    // slots13_1 :  "/src/sprites/Symbols/Bonus/Bonus 02.png",
    // slots13_2 :  "/src/sprites/Symbols/Bonus/Bonus 03.png",
    // slots13_3 :  "/src/sprites/Symbols/Bonus/Bonus 04.png",
    // slots13_4 :  "/src/sprites/Symbols/Bonus/Bonus 05.png",
    // slots13_5 :  "/src/sprites/Symbols/Bonus/Bonus 06.png",
    // slots13_6 :  "/src/sprites/Symbols/Bonus/Bonus 07.png",
    // slots13_7 :  "/src/sprites/Symbols/Bonus/Bonus 08.png",
    // slots13_8 :  "/src/sprites/Symbols/Bonus/Bonus 09.png",
    // slots13_9 :  "/src/sprites/Symbols/Bonus/Bonus 10.png",
    // slots13_10:  "/src/sprites/Symbols/Bonus/Bonus 11.png",
    // slots13_11:  "/src/sprites/Symbols/Bonus/Bonus 12.png",
    // slots13_12:  "/src/sprites/Symbols/Bonus/Bonus 13.png",
    // slots13_13:  "/src/sprites/Symbols/Bonus/Bonus 14.png",
    // slots13_14:  "/src/sprites/Symbols/Bonus/Bonus 15.png",
    // slots13_15:  "/src/sprites/Symbols/Bonus/Bonus 16.png",
    // slots13_16:  "/src/sprites/Symbols/Bonus/Bonus 17.png",
    // slots13_17:  "/src/sprites/Symbols/Bonus/Bonus 18.png",
    // slots13_18:  "/src/sprites/Symbols/Bonus/Bonus 19.png",
    // slots13_19:  "/src/sprites/Symbols/Bonus/Bonus 20.png",
    // slots13_20:  "/src/sprites/Symbols/Bonus/Bonus 21.png",
    // slots13_21:  "/src/sprites/Symbols/Bonus/Bonus 22.png",
    // slots13_22:  "/src/sprites/Symbols/Bonus/Bonus 23.png",
    // slots13_23:  "/src/sprites/Symbols/Bonus/Bonus 24.png",
    // slots13_24:  "/src/sprites/Symbols/Bonus/Bonus 25.png",
    // slots13_25:  "/src/sprites/Symbols/Bonus/Bonus 26.png",
    // slots13_26:  "/src/sprites/Symbols/Bonus/Bonus 27.png",
    // slots13_27:  "/src/sprites/Symbols/Bonus/Bonus 28.png",
    // slots13_28:  "/src/sprites/Symbols/Bonus/Bonus 29.png",
    // slots13_29:  "/src/sprites/Symbols/Bonus/Bonus 30.png",
    // slots13_30:  "/src/sprites/Symbols/Bonus/Bonus 31.png",
    // slots13_31:  "/src/sprites/Symbols/Bonus/Bonus 32.png",
    // slots13_32:  "/src/sprites/Symbols/Bonus/Bonus 33.png",
    // slots13_33:  "/src/sprites/Symbols/Bonus/Bonus 34.png",
    // slots13_34:  "/src/sprites/Symbols/Bonus/Bonus 35.png",
    // slots13_35:  "/src/sprites/Symbols/Bonus/Bonus 36.png",

    // firesheet: "src/sprites/FireSheet.png",
    // fire_1 :  "/src/sprites/Fire/Fire (1).png",
    // fire_2 :  "/src/sprites/Fire/Fire (2).png",
    // fire_3 :  "/src/sprites/Fire/Fire (3).png",
    // fire_4 :  "/src/sprites/Fire/Fire (4).png",
    // fire_5 :  "/src/sprites/Fire/Fire (5).png",
    // fire_6 :  "/src/sprites/Fire/Fire (6).png",
    // fire_7 :  "/src/sprites/Fire/Fire (7).png",
    // fire_8 :  "/src/sprites/Fire/Fire (8).png",
    // fire_9 :  "/src/sprites/Fire/Fire (9).png",
    // fire_10:  "/src/sprites/Fire/Fire (10).png",
    // fire_11:  "/src/sprites/Fire/Fire (11).png",
    // fire_12:  "/src/sprites/Fire/Fire (12).png",
    // fire_13:  "/src/sprites/Fire/Fire (13).png",
    // fire_14:  "/src/sprites/Fire/Fire (14).png",
    // fire_15:  "/src/sprites/Fire/Fire (15).png",
    // fire_16:  "/src/sprites/Fire/Fire (16).png",
    // fire_17:  "/src/sprites/Fire/Fire (17).png",
    // fire_18:  "/src/sprites/Fire/Fire (18).png",
    // fire_19:  "/src/sprites/Fire/Fire (19).png",
    // fire_20:  "/src/sprites/Fire/Fire (20).png",
    // fire_21:  "/src/sprites/Fire/Fire (21).png",
    // fire_22:  "/src/sprites/Fire/Fire (22).png",
    // fire_23:  "/src/sprites/Fire/Fire (23).png",
    
}



export const staticData = {
    // logoURL: "https://cccdn.b-cdn.net/1584464368856.png",
    // logoURL:  "/static/logo.png").default,
    Background:  "src/sprites/Background.jpg",
};

export const fontData = ["Montserrat"];



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.wav",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.wav",
        spinWheelMusic: "src/sounds/spinWheel.mp3"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}